package io.github.flyingpig525.data.auth.exception

class UserAlreadyExistsException : Exception()